### PR TITLE
Change error message if OECI is in maintenance

### PR DESCRIPTION
**Pull request by KentShikama**
Resolves https://github.com/codeforpdx/recordexpungPDX/issues/1069

~~The message "The eCourt site is offline during the 4th weekend of each month between 6 PM PST on Friday until noon on Sunday. During this time, record search will not function." will only show during the time period in which it applies.~~

Screen Shot 2020-04-26 at 8 03 47 AM

### CODE REVIEW

**Comment by hmarcks** [comment]
Do you think we should persist the message about the downtime window (like we have now) since it's such a big block of time? Then repeat the error message like you have it if they get the response.

**Comment by KentShikama** [comment]
Are you suggesting we implement something on the frontend like

```
if time.now() is 4th weekend of the month:
    display message on OECI login
```

**Comment by hmarcks** [comment]
I'm just suggesting we leave the message there all the time, and show the error message you created if the form is submitted and we get the service down response:
Screen_Shot_2020-04-26_at_12_30_19_PM

**Comment by wittejm** [comment]
I agree the message about downtime should show always, so the user isn't surprised about this issue.

**Comment by KentShikama** [comment]
@hmarcks @wittejm Got it. I reverted that portion.

**Pull request merged**
