### PR TITLE
add prod deploy targets and update docs

### PR DESCRIPTION
**Pull request by kenichi**
* adds `prod` and supporting deploy targets in src/ops/Makefile
* adds `frontend_restart` and doc reference in main Makefile
* updates relevant files in doc/

NEEDS TESTING

### CODE REVIEW

**Comment by KentShikama** [comment]
I haven't put much effort into understanding yet but I'm not quite clear which git tag/branch the production deploy uses. Do you still have to manually `git pull origin master` (or whatever branch you want to run) or is the source code somehow packaged into the docker image?

**Comment by kenichi** [comment]
Yes, it is currently up to the deployer to have their source tree in a valid state: clean working tree on the proper branch. I left proper SCM out of the make targets since I wasn't sure of the branching strategy moving forward.

**Comment by kenichi** [comment]
here's a gist of this in action https://gist.github.com/kenichi/b3a5355b5b4fb3cc7cf027364dd44033

**Comment by kenichi** [comment]
rebased from master and force pushed

**Pull request merged**
