### PR TITLE
Balance banner

### PR DESCRIPTION
**Pull request by Ark20**
Added Balance Due banner in case detail block. issue: #1227

### CODE REVIEW

**Comment by hmarcks** [comment]
Hi @Ark20 , we use Tachyons for our css framework ([more info here](http://dev.huntermarcks.net/design-system/#css-framework)), so could you please use a class combo like `<p className="bg-washed-red fw6 br3 pv2 ph3 ma2">` and remove the css?

The styles you made look good, but this allows us to avoid new css and more easily keep styles consistent when many folks are working on the app. Thanks!

**Comment by Ark20** [comment]
Thanks for the tachyon link and tips @hmarcks, I removed the additional css

**Comment by hmarcks** [comment]
👍 thanks, I'll let @wittejm or @KentShikama approve the js

**Comment by wittejm** [comment]
Code looks good for this, but looking at it again I need to revisit the design: 
@hmarcks @KentShikama @michaelzhang43 

Pulling in comments from the related issue #1191 
> Kent: I realized that if there are multiple charges in a case, it is not clear which charge the balance due is attached to.

> Hunter: Does it matter what charge in the case it relates to, or do we just need to know the case has a balance? 

Now that I'm looking a case with two charges, this is what we get:

balance_banner_two_charges

"Becomes" sounds like it only refers to one thing, but the charges are what become eligible, not the case. This especially should be clear when only some of the charges are eligible.

I think this could be improved by tweaking the language to "Charges become eligible when balance is paid"

Thoughts @hmarcks ?

@Ark20 this PR is coming from a branch on the main repo, but I saw you made your earlier PRs from your own clone. This one will be fine to merge as is, but for next time just remember to PR from your clone.

**Comment by hmarcks** [comment]
Ah, good catch. As long as a case balance causes all charges in a case to be ineligible, then I like your language update.

I guess "Eligible charges become eligible when balance is paid" is more accurate, but awkward.

**Comment by wittejm** [comment]
"Charges are ineligible until balance is paid"?

**Comment by hmarcks** [comment]
I like it

**Comment by Ark20** [comment]
Thanks @hmarcks @wittejm. I must have gotten things mixed up when I rebased but I'll make sure to make PRs from my clone going forward

**Pull request closed without merging**
