### PR TITLE
react-router implemented

### PR DESCRIPTION
**Pull request by ForrestLonganecker**
I have implemented React-Router to serve as a way to provide page-history and pages for search/account/admin/etc...

I currently have it set up for the only page that is in place(Search) but have put the routes in place for all the other pages in the nav-bar.

This way you will be able to use the RecordSearch component implementation to know how to get the other pages up and running.

It now appends the appropriate path-name to the URL and clears it when you log-out.

I am not sure why it says "Can't automatically merge". 

Please let me know any feedback you have!

### CODE REVIEW

**Comment by ForrestLonganecker** [comment]
After looking at the conflict it appears that it is missing axios and has fontawesome in a different place in the package.json file.

**Comment by maxkwallace** [comment]
@ForrestLonganecker hey, thanks for the PR! 

I took a brief look at the code and it looks like there's some overlap with https://github.com/codeforpdx/recordexpungPDX/pull/285

https://github.com/codeforpdx/recordexpungPDX/pull/285 was submitted two weeks ago (and I reviewed it then) so ideally I'd like to move ahead with that PR first. But this depends on Chris since he submitted the PR and I haven't heard from him since then.

@cjbreaux hey! Were you planning on addressing my requested changes in https://github.com/codeforpdx/recordexpungPDX/pull/285 and trying to get it merged in? If no, that's totally okay, just need to know what's up, since other folks would like to make changes in those areas as well. Were you planning on finishing the PR or would you be open to someone else making the necessary changes to get it merged in?

**Comment by cjbreaux** [comment]
Hi! Yes, I'm finishing the PR up right now and should have the changes
submitted shortly!

**Comment by maxkwallace** [comment]
@cjbreaux sounds good! @ForrestLonganecker I'm going to re-review https://github.com/codeforpdx/recordexpungPDX/pull/285 first and hopefully we can get that merged in next. Then we can rebase this branch on master to bring it up to date with Chris's changes in https://github.com/codeforpdx/recordexpungPDX/pull/285, and then work on merging this branch in, so you can make any improvements to the React Router functionality in https://github.com/codeforpdx/recordexpungPDX/pull/285 as needed. Thanks!

**Comment by ForrestLonganecker** [comment]
Sorry, I didn't notice the overlap, thanks for catching that!

**Comment by maxkwallace** [comment]
@ForrestLonganecker FYI, https://github.com/codeforpdx/recordexpungPDX/pull/285 has been merged, so you're welcome to continue working on this PR now, or open a new one if you still want to make changes in this area.

**Pull request closed without merging**
