### PR TITLE
Fixed COMPILED.pdf and updated PDF layout

### PR DESCRIPTION
**Pull request by emko-274**
- added 50px margin to PDF forms
- moved "Assumptions" block under "Disclaimer" in summary PDF

to-do: 
- update build_zip form filling tests
- add clear button test to search panel test file

### CODE REVIEW

**Comment by wittejm** [comment]
Why did you have to modify the stylesheet?

**Comment by emko-274** [comment]
Michael requested that we add a bigger margin to the PDF files, which I did by modifying the stylesheet.

**Comment by wittejm** [comment]
And you're customizing the stylesheet that we were downloading from
somewhere?

**Comment by wittejm** [comment]
It was surprising to see such a large new file. I think that comments in
the file mentioning where it came from, and noting the change you made from
the original, would be helpful

**Comment by emko-274** [comment]
Yes, the new file just contains the text from the source that was originally being requested from (https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css), with a one-line edit. Is it alright if I add the comment in the file where the new one is read from? I'm not sure how to write comments in the txt file so that they aren't read into the string that's supposed to contain only CSS, other than by skipping lines when reading, which I think might be awkward.

**Comment by wittejm** [comment]
Ah, that's why it's a txt file. Yea, explaining it and showing the URL in
the comment when you call the file sounds good

**Comment by emko-274** [comment]
Okay, I added the comment

**Review by wittejm — APPROVED** [review]

**Pull request merged**
