### PR TITLE
Automatically register all endpoints

### LINKED ISSUE #88: Automate registering of endpoint routes in expungeservice/app.py
Currently, when adding endpoints to the backend, routes for the endpoints (found in `src/backend/expungeservice/endpoints/`) must be manually added to the `create_app` method of `src/backend/expungeservice/app.py`, e.g.:

```
    # Register endpoint routes here:
    hello.register(app)
    auth.register(app)
```

The goal would be to alter `src/backend/expungeservice/app.py` to search the endpoint directory and register the endpoint routes itself, so that regardless of removals or additions to the endpoints, the backend will find them and register them.

### This task is done when...
 - Routes for new endpoints for the backend don't need to be manually added to `src/backend/expungeservice/app.py`

### PR DESCRIPTION
**Pull request by KentShikama**
Closes #88

All endpoints have the method signature register(app) and thus we can use that assumption to reflectively call those methods.

### CODE REVIEW

**Comment by NickSchimek** [comment]
This looks great! @erikjasso @wittejm @ash-tamraz do you want to take a look?

**Comment by erikjasso** [comment]
Looks good to me.

**Comment by erikjasso** [comment]
@KentShikama Could you add a test for this feature? Something simple to verify it -- there must be a way to check if a specific module has been imported?

**Comment by KentShikama** [comment]
@erikjasso If you comment out (line 42) register_fn(app), the following tests will fail as the endpoints do not get registered.

```
tests/endpoints/test_auth.py F.FFFFFF                        
tests/endpoints/test_oeci_login.py FF                        
tests/endpoints/test_search.py F                             
tests/endpoints/test_users.py FF.FFFFF.FFFFFFFF.F
```

In essence, I would say it is rather well tested already. It looks like there is no test for the `hello` endpoint but would like to see one for that?

**Pull request merged**
