### PR TITLE
Add ID to PDF & Search Summaries

### PR DESCRIPTION
**Pull request by JeremyC3**
Met with Michael & CLEAR members, confirmed that adding charge ID in PDF summary + Search Summary would be useful for lookup when clients bring in previously printed-out forms. Fixed typo in markdown file for PDF summary.

### CODE REVIEW

**Comment by JeremyC3** [comment]
Failing tests noted. Expected test results will be modified to reflect the new formatting, if acceptable.

**Review by KentShikama — COMMENTED** [review]
Yup feel free to just update the tests!

**Comment by JeremyC3** [comment]
Will be making additional changes before new PR created.

**Comment by JeremyC3** [comment]
Amended both backend & frontend tests to reflect changes made.

**Review by KentShikama — APPROVED** [review]

**Pull request merged**
