### PR TITLE
Add "$ owed" to charge one line summary if applicable

### PR DESCRIPTION
**Pull request by KentShikama**
Linking https://github.com/codeforpdx/recordexpungPDX/issues/1191 

Screenshot of charge summary panel. Note that the third line is highlighted as I'm hovering over it with my mouse:

Screen Shot 2020-06-11 at 6 28 58 AM

### CODE REVIEW

**Comment by michaelzhang43** [comment]
This is good. It would be better if we could insert the dollar sign symbol Hunter drew up in Summary Option 2 on the related issue. I'm thinking that we can push a kind of final release to the defense lawyers on June 19. With that timeframe in mind, would it be better to do this or the dollar sign symbol?

**Comment by KentShikama** [comment]
@hmarcks Do you have HTML for that $ symbol or is that just some icon on Sketch?

**Comment by KentShikama** [comment]
@michaelzhang43 We can discuss more tonight on release logistics.

**Comment by hmarcks** [comment]
`<span class="visually-hidden">Money is owed for this case</span><span aria-hidden="true" class="fw6 red bg-washed-red br2 ph2 ml2">$</span>`

**Comment by wittejm** [comment]
Rebased and applied @hmarcks 's version.

with_dollar_badges

**Pull request merged**
