### PR TITLE
Upgrade almost all frontend dependencies

### PR DESCRIPTION
**Pull request by monocle**
* This will upgrade all of the dependencies execpt `react-router-dom`, which will be done in the future.
* `@reach/disclosure` was removed due to incompatibility with `react v18`. Custom hooks were written to replace it's functionality. This affected the `PartnerTable`, `EditingGuide`, `ChargeTypeRule` and `ExpungmentRules` components.
* Along the way, an `SVG` component was created to remove some of the noisiness of the svg code. Additional components will be refactors to use this in the future.
* More tests were written.

### CODE REVIEW

**Review by KentShikama — COMMENTED** [review]
Still trying to navigate this change. Would you mind helping me figure out how the SVGs are used?

**Comment by monocle** [comment]
@KentShikama Currently, it's only used in PartnerTable:

https://github.com/codeforpdx/recordexpungPDX/blob/7da9f14032df87519a79f303155b198aa980e5ae/src/frontend/src/components/PartnerTable/index.tsx#L83-L88

All of the props are forwarded to the underlying `<svg>` element which just has a couple of defaults:

https://github.com/codeforpdx/recordexpungPDX/blob/7da9f14032df87519a79f303155b198aa980e5ae/src/frontend/src/components/common/SVG/index.tsx#L23-L26

The `SVG` component has all of the `svg`s in the app:

https://github.com/codeforpdx/recordexpungPDX/blob/7da9f14032df87519a79f303155b198aa980e5ae/src/frontend/src/components/common/SVG/index.tsx#L9-L14

But I didn't put those in yet since I didn't want to add more component refactoring in this PR. The other `SVG`s would look like:

image

image

image

**Review by KentShikama — APPROVED** [review]
LGTM

**Comment by KentShikama** [comment]
@monocle Not sure if you can see this so I'm going to post here. You've closed 9 critical vulnerabilities over your past couple PRs 🥳 I'm not sure of any of them were real vulnerabilities in our site but its nice to see nonetheless.

Screen Shot 2023-01-20 at 9 04 10 AM

**Pull request merged**
