### PR TITLE
Rename renderX methods in Charge.tsx hierarchy to buildX

### PR DESCRIPTION
**Pull request by faranilucero**
Resolves: #1184

### CODE REVIEW

**Comment by faranilucero** [comment]
Thanks, I appreciate the opportunity to learn!  However, looks like I don't have write permission to merge this PR.

**Comment by wittejm** [comment]
Oh right. I've merged the PR but also invited you to join codeforpdx so you can merge approved PRs in the future.

**Comment by faranilucero** [comment]
Thanks for the invite Jordan! Looking forward to learning a lot and helping where I can.

**Comment by wittejm** [comment]
Awesome! If there's another issue you want to tackle but have questions or aren't sure exactly what to do, feel free to ask and we'll help out.

**Comment by KentShikama** [comment]
I forgot to add Question.tsx to the issue: https://github.com/codeforpdx/recordexpungPDX/blob/c3121f00b57f11fd5b45639b062caae453f06729/src/frontend/src/components/RecordSearch/Record/Questions.tsx#L45 .

**Pull request merged**
