### PR TITLE
[WIP] Add manual page

### PR DESCRIPTION
**Pull request by wittejm**
Empty for now. Start of #1042 

The page appears at `/manual` and is linked in the nav bar for logged-in users.

There's also a link added to the Landing page, but it's not styled, ~~and it doesn't work!~~ Edit: fixed.

### CODE REVIEW

**Comment by wittejm** [comment]
@hmarcks you can push to this branch.

The header just conditionally renders everywhere if the user is logged in. What do you think it should look like if the user isn't logged in? Should the user be expected to hit the back button to navigate elsewhere?

**Comment by hmarcks** [comment]
@wittejm Can you just show the same <nav> when on /manual and not logged in?

Logged in version looks good, thank you

**Comment by wittejm** [comment]
yes, but I think it should exclude the Search and Logout links but include the Login button as well as Manual. While we're at it, should we have a Home link for the landing page?

**Comment by hmarcks** [comment]
Yeah, it should only have logo, Manual, and Log In. I think I'll just add a "back" link in the header of the Manual and make the logo a link to home.

**Comment by wittejm** [comment]
Ok, cool. And, should the login page look the way it does now, or should we add the manual/ other nav content there too?

**Comment by hmarcks** [comment]
hmm, good question, I think it's fine how it is

**Comment by wittejm** [comment]
@hmarcks I decided to make a feature branch for this on the main repo, so that we don't accidentally disrupt each other's work by pushing directly to this branch. closing this PR and preplacing it with the new [WIP] PR

**Pull request closed without merging**
