### PR TITLE
deleted typo (repeated word)

### PR DESCRIPTION
**Pull request by Matth5050**
deleted the second instance of the phrase "recent changes" and added a space after the preceding period.

Not a specific ticket but found this while going through the site. This is my first commit and I hope to contribute more going forward.

### CODE REVIEW

**Review by KentShikama — COMMENTED** [review]
Nice catch. Are you able to update the snapshot tests?

**Comment by Matth5050** [comment]
```
watchman warning:  opendir(/Users/mherbert/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.15.5/ext/ffi_c/.gem.20221023-97572-bdy5zg) -> Permission denied. Marking this portion of the tree deleted
To clear this warning, run:
`watchman watch-del '/Users/mherbert' ; watchman watch-project '/Users/mherbert'`

jest-haste-map: duplicate manual mock found: VSCodeMementoMock
  The following files share their name; please delete one of them:
    * <rootDir>/.vscode/extensions/brapifra.phpserver-3.0.2/out/__mocks__/VSCodeMementoMock.js
    * <rootDir>/.vscode/extensions/brapifra.phpserver-3.0.2/src/__mocks__/VSCodeMementoMock.ts
    
   ```
   
   After A few more of those "jest-haste_map: duplicate..." warnings the final output is this:
   
   ```
   Error: Cannot parse /Users/mherbert/Library/Group Containers/UBF8T346G9.OneDriveStandaloneSuite/OneDrive.noindex/OneDrive/Desktop/Exchange_Rate-main/package.json as JSON: Unexpected token  in JSON at position 0
    at Object.worker (/usr/local/lib/node_modules/jest/node_modules/jest-haste-map/build/worker.js:154:13)
    at execFunction (/usr/local/lib/node_modules/jest/node_modules/jest-worker/build/workers/processChild.js:137:17)
    at execHelper (/usr/local/lib/node_modules/jest/node_modules/jest-worker/build/workers/processChild.js:116:5)
    at execMethod (/usr/local/lib/node_modules/jest/node_modules/jest-worker/build/workers/processChild.js:120:5)
    at process.messageListener (/usr/local/lib/node_modules/jest/node_modules/jest-worker/build/workers/processChild.js:38:7)
    at process.emit (node:events:527:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) 
```  

   To fix this I've tried:
  
    1. running `watchman watch-del '/Users/mherbert' ; watchman watch-project '/Users/mherbert'`
    2. adding `"modulePathIgnorePatterns": ["<rootDir>/build","<rootDir>/vendor"]` to the package.son under jest
    3. adding `"exclude": ["**/__mocks__/*", "../../node_modules", "build", "src/**/*.test.ts", "src/**/*.test.tsx"]` to 
       package.json

**Comment by Matth5050** [comment]
I'll keep trying a few things

**Comment by Matth5050** [comment]
Deleted jest and some extensions now only have this:

```
Error: ETIMEDOUT: connection timed out, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:471:19)
    at getContent (/usr/local/lib/node_modules/jest/node_modules/jest-haste-map/build/worker.js:137:22)
    at Object.worker (/usr/local/lib/node_modules/jest/node_modules/jest-haste-map/build/worker.js:165:23)
    at execFunction (/usr/local/lib/node_modules/jest/node_modules/jest-worker/build/workers/processChild.js:137:17)
    at execHelper (/usr/local/lib/node_modules/jest/node_modules/jest-worker/build/workers/processChild.js:116:5)
    at execMethod (/usr/local/lib/node_modules/jest/node_modules/jest-worker/build/workers/processChild.js:120:5)
    at process.messageListener (/usr/local/lib/node_modules/jest/node_modules/jest-worker/build/workers/processChild.js:38:7)
    at process.emit (node:events:527:28)

**Comment by monocle** [comment]
@Matth5050 I'll help you debug this on Slack.

**Comment by Matth5050** [comment]
I updated my snapshot and the checks have passed. Thank you @monocle and @KentShikama for the help and patience!

**Review by KentShikama — APPROVED** [review]

**Pull request merged**
