### PR TITLE
Endpoint users cleanup

### PR DESCRIPTION
**Pull request by wittejm**
This PR has some refactoring / code cleanup without adding any new features.

- POST /api/users is renamed to /api/user, to match our design update.
- The test cases for user, users, and auth endpoints are all cleaned up by removing redundant code.

(is a subset of my closed PR #392 )

### CODE REVIEW

**Comment by NickSchimek** [comment]
As a convention I prefer to have all endpoints that involves the same resource in one file. Otherwise if the pattern in the PR is propagated then we may end up with 5 user files each pertaining to a different HTTP request involving the same `user` resource. Could we perhaps simply rename the original `users.py` file to `user.py` ❓

**Comment by wittejm** [comment]
@NickSchimek Ok, I merged the two endpoints into a single source file.py

**Comment by wittejm** [comment]
I went looking into a good pattern for GET all users vs GET one user and in this Flask documentation 

https://flask.palletsprojects.com/en/1.1.x/views/

they use the same MethodView class with the URI /users/. So... I think I'll refactor this again, put it all back into a shared /users/ endpoint rather than separated the way they are now. Fortunately I think the frontend is only connected to GET /users/ so far, so no added work there. @ForrestLonganecker , is that right?

Also applies to issues #37

**Comment by ForrestLonganecker** [comment]
That should be correct, and the get uses endpoint is not yet integrated
into the frontend so it won't cause issues there either!

**Pull request merged**
