### PR TITLE
Update technical difficulties message to include a contact email

### PR DESCRIPTION
**Pull request by swervinerv**
The technical difficulties message when attempting to log in has been updated to what is below. Let me know if there are any suggestions for better copy.

`We're experiencing technical difficulties, please contact help@recordsponge.com`

### CODE REVIEW

**Comment by wittejm** [comment]
I think the code reformatting should go in a different PR and we can keep this just a one line change for the issue. Message text sounds good though.

**Comment by KentShikama** [comment]
I've created a new issue to install an auto-formatter for the frontend: https://github.com/codeforpdx/recordexpungPDX/issues/1215

**Comment by swervinerv** [comment]
@KentShikama It looks like there is currently a `pre-commit` hook specified in the package file, which is what caused the formatting changes in this PR. I can remove that on my local and just push the one line change if we would like to wait on this formatting.

```"husky": {
  "hooks": {
    "pre-commit": "lint-staged"
  }
},
"lint-staged": {
  "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}": [
    "prettier --single-quote --write",
    "git add"
  ]
}

**Comment by KentShikama** [comment]
@swervinerv Yeah it has been long overdue to get prettier running on the frontend. I've just merged https://github.com/codeforpdx/recordexpungPDX/pull/1219. This PR will need a rebase.

**Pull request merged**
