### PR TITLE
Add v1.0.0 Changelog updates

### PR DESCRIPTION
**Pull request by KentShikama**
I have left out anything that wasn't "user-facing" (where "Add mocked OECI endpoints" is borderline included). I apologize if I left anything out. Note this doesn't include anything post-v1.0.0. Ordering is based on PR # where the first related PR is the key used. I have mostly kept the PR titles and aggressively grouped together related PRs.

I've also moved the Changelog to the root directory. I think it makes more sense to keep track of the changes across the entire project. Perhaps we can break it down frontend vs backend if the project becomes large enough.

### CODE REVIEW

**Comment by NickSchimek** [comment]
Thanks @KentShikama This looks good to me. Let's keep this PR open for a couple more days. There are a few more things I want to add to this.

**Comment by NickSchimek** [comment]
Or we can merge this, and I can update the change log in the PR, assuming we're not planning on releasing V1 once this is merged?

**Comment by KentShikama** [comment]
@wittejm has already tagged a v1.0 release (see https://github.com/codeforpdx/recordexpungPDX/releases).

**Comment by KentShikama** [comment]
By "[n]ote this doesn't include anything post-v1.0.0", I meant that there are changes between the v1.0 tag that @wittejm made and the current HEAD of master that I haven't included. Are these the "few more things" you wanted to add?

**Comment by NickSchimek** [comment]
No, those are not what I wanted to add. Thanks for clarifying. I'm fine with these changes. Thanks!

**Pull request merged**
