### PR TITLE
Fix case where disposition is not set

### LINKED ISSUE #578: Fix case where disposition is not set
Originally discovered by Michael Zhang.

Sometimes there are charges without a corresponding disposition in the OECI database. This will just crash the server saying that upon attempt at serialization disposition.date didn't exist as disposition was None.

### PR DESCRIPTION
**Pull request by KentShikama**
Closes #578 

Sometimes there are charges without a corresponding disposition in the OECI database. This will just crash the server saying that upon attempt at serialization disposition.date didn't exist as disposition was None.

~~TODO: I still owe a non-manual test for this issue. However, I've gone ahead and pushed this to https://recordexpungpdx.herokuapp.com/ so that Michael won't be blocked from testing.~~

Edit: Tests have been added.

### CODE REVIEW

**Comment by NickSchimek** [comment]
@KentShikama It would be good to go through and hook up the record fixtures already in place to create a system test for the entire backend. Similar to what is done in `test_crawler_expunger.py`. Because the record fixtures cover a lot of different real world use cases that would've caught this issue.

**Comment by NickSchimek** [comment]
>  I've gone ahead and pushed this to https://recordexpungpdx.herokuapp.com/ so that Michael won't be blocked from testing

Thanks for getting that pushed. 🎉

**Comment by KentShikama** [comment]
@NickSchimek @wittejm PTAL as I've added the backend tests that I owe.

**Comment by wittejm** [comment]
Cool, LGTM

**Comment by KentShikama** [comment]
@NickSchimek I've addressed unused imports with https://github.com/codeforpdx/recordexpungPDX/pull/588

**Pull request merged**
